apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2  # Nombre de pods
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: syrinechelbi/simple-django-app:latest 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80  # Port accessible à l'extérieur
      targetPort: 8000  # Port interne utilisé par le conteneur
  type: LoadBalancer
